/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KonkurrensRouteImport } from './routes/konkurrens'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LagenhetObjektNrRouteImport } from './routes/lagenhet/$objektNr'

const KonkurrensRoute = KonkurrensRouteImport.update({
  id: '/konkurrens',
  path: '/konkurrens',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LagenhetObjektNrRoute = LagenhetObjektNrRouteImport.update({
  id: '/lagenhet/$objektNr',
  path: '/lagenhet/$objektNr',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/konkurrens': typeof KonkurrensRoute
  '/lagenhet/$objektNr': typeof LagenhetObjektNrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/konkurrens': typeof KonkurrensRoute
  '/lagenhet/$objektNr': typeof LagenhetObjektNrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/konkurrens': typeof KonkurrensRoute
  '/lagenhet/$objektNr': typeof LagenhetObjektNrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/konkurrens' | '/lagenhet/$objektNr'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/konkurrens' | '/lagenhet/$objektNr'
  id: '__root__' | '/' | '/konkurrens' | '/lagenhet/$objektNr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KonkurrensRoute: typeof KonkurrensRoute
  LagenhetObjektNrRoute: typeof LagenhetObjektNrRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/konkurrens': {
      id: '/konkurrens'
      path: '/konkurrens'
      fullPath: '/konkurrens'
      preLoaderRoute: typeof KonkurrensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lagenhet/$objektNr': {
      id: '/lagenhet/$objektNr'
      path: '/lagenhet/$objektNr'
      fullPath: '/lagenhet/$objektNr'
      preLoaderRoute: typeof LagenhetObjektNrRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KonkurrensRoute: KonkurrensRoute,
  LagenhetObjektNrRoute: LagenhetObjektNrRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
